name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: SIDDH31
          outputs: |
            dist/github-snake.svg?color_snake=#ffffff&color_dots=#ebe1d3,#c4a274,#8b5e34,#5c3d1e,#3a2314
            dist/github-snake-dark.svg?color_snake=#ffffff&color_dots=#1f140e,#5c3d1e,#8b5e34,#c4a274,#ebe1d3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
